Repository SOLUX-2019/SantaIsSanta, pull requests merged in 2022-02, with the labels that each got.

#16 로그인/랜딩 페이지 연결
  client/src/Login/Login.js
  server/index.js
Labels: enhancement

#21 login 기능 구현
  server/index.js
Labels: 민지, Back-end

#24 state 설정
  client/src/Join/Join.js
  client/src/Join/styledJoin.js
  client/src/Login/Login.js
  client/src/Login/styledLogin.js
  client/src/Profile/ModifyProfile.js
Labels: feat, Front-end

#25 navbar 지역별 링크 연결
  client/src/NavBar/NavBar.js
Labels: feat, Front-end

#27 Feat/community
  .idea/SantaIsSanta.iml
  .idea/modules.xml
  .idea/runConfigurations.xml
  .idea/vcs.xml
  .idea/workspace.xml
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/MyPage/BadgeCollection.js
  client/src/MyPage/MyPage.js
  client/src/community/Comment.js
  client/src/community/PostList/Pagination.js
  client/src/community/PostList/SearchBar.js
  client/src/community/WritingPage.js
  client/src/community/WritingPage/Writer.js
  client/src/community/WritingPage/WritingPage.js
  client/src/community/WritingPage/styledWritingPage.js
Labels: feat, 주은, Front-end

#30 Feat/my page
  client/src/MyPage/Badge.js
  client/src/MyPage/BadgeCollection.js
  client/src/MyPage/MyPage.js
  client/src/MyPage/PostList.js
  client/src/MyPage/Profile.js
Labels: 주은, Front-end

#31 마이페이지 회원 정보 불러오기
  server/index.js
Labels: 민지, Back-end

#32 Feature/#29
  client/package-lock.json
  client/src/Login/Login.js
  client/src/Mountain/InfoPage/Mountain.js
  client/src/Mountain/InfoPage/MountainHeader.js
  client/src/Mountain/InfoPage/MountainInfo.js
  client/src/Mountain/InfoPage/MountainLoc.js
  client/src/Mountain/InfoPage/MountainMap.js
  client/src/Mountain/InfoPage/MountainReview.js
  client/src/Mountain/InfoPage/styledInfoPage.js
  client/src/Mountain/RegionPage/MountainList.js
  client/src/Mountain/RegionPage/RegionPage.js
  client/src/Mountain/RegionPage/styledRegionPage.js
  client/src/Profile/ModifyProfile.js
  server/package-lock.json
Labels: feat, 서인, Front-end

#34 Feat/nav
  client/src/NavBar/NavBar.js
  client/src/NavBar/styledNav.js
  client/src/community/LinkButton.js
  client/src/community/PostList/Pagination.js
  client/src/community/PostList/SearchBar.js
  client/src/community/PostList/styledPostList.js
  client/src/community/PostView.js
  client/src/community/WritingPage/WritingPage.js
  client/src/community/WritingPage/styledWritingPage.js
Labels: feat, 주은, Front-end

#35 게시글 불러오기/수정 및 코드 정리
  server/index.js
Labels: 민지, Back-end

#37 /auth 주석처리
  server/index.js
Labels: duplicate, 민지, Back-end

#39 Feat/my page
  client/src/MyPage/BadgeCollection.js
  client/src/MyPage/MyPage.js
  client/src/MyPage/PostList.js
  client/src/MyPage/Profile.js
  client/src/MyPage/styledMyPage.js
Labels: feat, 주은, Front-end

#40 Feature/#33
  client/src/Join/Join.js
  client/src/Login/Login.js
  client/src/Profile/ModifyProfile.js
Labels: feat, 서인, Front-end

#42 pid로 게시글 하나 불러오기
  server/index.js
Labels: 민지, Back-end

#45 댓글 조회/수정
  server/index.js
Labels: 민지, Back-end

#46 get요청 qurey 설정변경
  server/index.js
Labels: 민지, Back-end

#48 Feat/community
  client/src/App.js
  client/src/MyPage/BadgeCollection.js
  client/src/community/Comment.js
  client/src/community/PostList/Pagination.js
  client/src/community/PostList/PostList.js
  client/src/community/PostList/PostListComponents.js
  client/src/community/PostList/PostListPage.js
  client/src/community/PostList/SearchBar.js
  client/src/community/PostList/styledPostList.js
  client/src/community/PostView.js
  client/src/community/WritingPage/Writer.js
  client/src/community/WritingPage/WritingPage.js
  client/src/community/styledComment.js
  client/src/community/styledPostView.js
  server/index.js
Labels: feat, 주은, Front-end

#51 Feat/community
  client/src/community/Comment.js
  client/src/community/PostView.js
  client/src/community/WritingPage/Writer.js
  client/src/community/WritingPage/WritingPage.js
Labels: feat, 주은, Front-end

#57 Feature/#56
  client/src/Join/Join.js
  client/src/Join/styledJoin.js
  client/src/Login/styledLogin.js
  client/src/Profile/ModifyProfile.js
Labels: feat, 서인, Front-end

#52 Feat/my page
  client/src/MyPage/MyPage.js
  client/src/MyPage/PostList.js
  client/src/MyPage/Profile.js
  client/src/Profile/ModifyProfile.js
Labels: feat, 주은, Front-end

#59 fix: 회원정보수정 페이지 코드오류 해결
  client/src/Profile/ModifyProfile.js
Labels: 서인, Front-end

#61 산 정보 조회/ 지역별 산 정보 리스트 조회
  server/index.js
  server/models/Mountain.js
  server/models/User.js
Labels: 민지, Back-end

#63 Feature/#60
  client/src/Join/Join.js
  client/src/Login/Login.js
  client/src/Profile/ModifyProfile.js
Labels: bug, 서인, Front-end

#62 Feat/login context
  client/src/App.js
  client/src/Login/Login.js
  client/src/LoginContext.js
  client/src/MyPage/MyPage.js
  client/src/MyPage/Profile.js
  client/src/NavBar/NavBar.js
  client/src/community/Comment.js
  client/src/community/PostView.js
  client/src/community/WritingPage/WritingPage.js
Labels: feat, 주은, Front-end

#64 지역별 산 정보 조회 코드 수정
  server/index.js
Labels: documentation, 민지, Back-end

#66 Feat/커뮤니티 페이지 글자수 제한
  client/src/MyPage/MyPage.js
  client/src/community/CharacterLimit.js
  client/src/community/Comment.js
  client/src/community/PostList/SearchBar.js
  client/src/community/PostView.js
  client/src/community/WritingPage/WritingPage.js
  client/src/community/styledComment.js
Labels: feat, 주은, Front-end

#69 게시글 검색 기능
  server/index.js
  server/models/Mountain.js
  server/package-lock.json
  server/package.json
Labels: 민지, Back-end

#70 게시글 코드 수정
  server/index.js
Labels: 민지, Back-end

#71 부분 검색 기능
  server/index.js
Labels: 민지, Back-end

#72 전체 카테고리로 검색
  server/index.js
Labels: 민지, Back-end

#75 Feature/#65
  client/src/Login/Login.js
  client/src/Mountain/InfoPage/Mountain.js
  client/src/Mountain/InfoPage/MountainHeader.js
  client/src/Mountain/InfoPage/MountainImg.js
  client/src/Mountain/InfoPage/MountainInfo.js
  client/src/Mountain/InfoPage/MountainLoc.js
  client/src/Mountain/InfoPage/MountainMap.js
  client/src/Mountain/InfoPage/MountainReview.js
  client/src/Mountain/RegionPage/MountainList.js
  client/src/assets/img/guemo.png
  client/src/assets/img/jirisan.png
  client/src/assets/img/juwang.png
  client/src/assets/img/mountainImg/가야산.png
  client/src/assets/img/mountainImg/강천산.png
  client/src/assets/img/mountainImg/계룡산.png
  client/src/assets/img/mountainImg/관악산.png
  client/src/assets/img/mountainImg/내연산.png
  client/src/assets/img/mountainImg/내장산.png
  client/src/assets/img/mountainImg/대둔산.png
  client/src/assets/img/mountainImg/덕유산.png
  client/src/assets/img/mountainImg/도봉산.png
  client/src/assets/img/mountainImg/두륜산.png
  client/src/assets/img/mountainImg/두타산.png
  client/src/assets/img/mountainImg/마이산.png
  client/src/assets/img/mountainImg/북한산.png
  client/src/assets/img/mountainImg/산방산.png
  client/src/assets/img/mountainImg/설악산.png
  client/src/assets/img/mountainImg/성산 일출봉.png
  client/src/assets/img/mountainImg/소백산.png
  client/src/assets/img/mountainImg/신불산.png
  client/src/assets/img/mountainImg/영주산.png
  client/src/assets/img/mountainImg/오대산.png
  client/src/assets/img/mountainImg/용눈이오름.png
  client/src/assets/img/mountainImg/운악산.png
  client/src/assets/img/mountainImg/월악산.png
  client/src/assets/img/mountainImg/월출산.png
  client/src/assets/img/mountainImg/응봉산.png
  client/src/assets/img/mountainImg/주왕산.png
  client/src/assets/img/mountainImg/지리산.png
  client/src/assets/img/mountainImg/칠갑산.png
  client/src/assets/img/mountainImg/태백산.png
  client/src/assets/img/mountainImg/한라산.png
  client/src/assets/img/mountainImg/황매산.png
  client/src/assets/img/palgak.png
  client/src/assets/img/palgong.png
Labels: feat, 서인, Front-end
