Repository SOLUX-2019/SantaIsSanta, pull requests merged in 2022-01, with the labels that each got.

#4 DB Schema 작성
  server/.gitignore
  server/index.js
  server/models/Mountain.js
  server/models/Post.js
  server/models/User.js
  server/package.json
Labels: feature, 민지, 한나, back

#5 DB 정보보호
  server/.gitignore
  server/config/key.js
  server/index.js
Labels: feature, 민지, back

#6 DB 정보보호
  server/config/prod.js
Labels: feature, 민지, back

#7 DB Schema 수정
  server/models/Comment.js
  server/models/Mountain.js
  server/models/Post.js
  server/models/User.js
Labels: docs, 민지, back

#8 비밀번호 암호화
  server/models/User.js
  server/package-lock.json
  server/package.json
Labels: feature, 민지, back

#13 refactor: styled-components 방식으로 css 수정
  client/src/Join/Join.js
  client/src/Join/styledJoin.js
  client/src/Login/Login.js
  client/src/Login/Login.module.css
  client/src/Profile/ModifyProfile.js
Labels: 서인, front
